---
# tasks file for drbd
  - rpm_key:
      state: present
      key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
  - name: add drbd repository
    yum:
      name: http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
      state: present
  - name: install drbd90-utils
    yum:
      name: drbd90-utils
      state: present

  - name: install  drbd90-util-sysvinit
    yum:
      name: drbd90-utils-sysvinit
      state: present

  - name: install kmod-drbd90
    yum:
      name: kmod-drbd90
      state: present

  - name: Add the DRBD module
    modprobe:
      name: drbd
      state: present
      
  - name: copy drbd.conf
    copy:
      src: "{{ role_path }}/files/drbd.conf"
      dest: /etc/modules-load.d/drbd.conf

  - selinux:
      state: disabled

  - name: disable firewalld
    service:
      name: firewalld
      state: stopped

  - name: install corosync
    yum:
      name: corosync
      state: present

  - name: install pcs pacemaker
    yum:
      name: pcs
      state: present
  - name: copy drbd0.res
    copy:
      src: "{{ role_path }}/files/drbd0.res"
      dest: /etc/drbd.d/drbd0.res
                                                                                                        
                                                                                                        
                                                                                       19,0-1        All
